FROM golang:1.15

WORKDIR /go/src
COPY ./src .

RUN go get -u github.com/cosmtrek/air && \
  go build -o /go/bin/air github.com/cosmtrek/air

COPY src/go.mod .
COPY src/go.sum .
RUN go mod download

CMD ["air", "-c", ".air.toml"]